-- MySQL Script generated by MySQL Workbench
-- 08/18/16 16:59:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NOT NULL,
  `project_objective` VARCHAR(45) NOT NULL,
  `started_date` DATE NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `cost` VARCHAR(45) NOT NULL,
  `fund_resources` VARCHAR(45) NOT NULL,
  `people_involve` VARCHAR(45) NOT NULL,
  `beneficiaries` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requirements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `requirements_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`donor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `donor_fname` VARCHAR(45) NOT NULL,
  `donor_lname` VARCHAR(45) NOT NULL,
  `donor_address` VARCHAR(45) NOT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`campaign` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campaign_name` VARCHAR(45) NOT NULL,
  `campaign_type` VARCHAR(45) NOT NULL,
  `donor_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Campaign_Donor1_idx` (`donor_Id` ASC),
  CONSTRAINT `fk_Campaign_Donor1`
    FOREIGN KEY (`donor_Id`)
    REFERENCES `mydb`.`donor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(45) NOT NULL,
  `admin_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requirements_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requirements_has_project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `requirements_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Requirements_has_Project_Project1_idx` (`project_id` ASC),
  INDEX `fk_Requirements_has_Project_Requirements_idx` (`requirements_id` ASC),
  CONSTRAINT `fk_Requirements_has_Project_Requirements`
    FOREIGN KEY (`requirements_id`)
    REFERENCES `mydb`.`requirements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requirements_has_Project_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`donor_has_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`donor_has_requirements` (
  `id` VARCHAR(45) NOT NULL,
  `donor_id` INT NOT NULL,
  `requirements_id` INT NOT NULL,
  `amount_donate` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Donor_has_Requirements_Requirements1_idx` (`requirements_id` ASC),
  INDEX `fk_Donor_has_Requirements_Donor1_idx` (`donor_id` ASC),
  CONSTRAINT `fk_Donor_has_Requirements_Donor1`
    FOREIGN KEY (`donor_id`)
    REFERENCES `mydb`.`donor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Donor_has_Requirements_Requirements1`
    FOREIGN KEY (`requirements_id`)
    REFERENCES `mydb`.`requirements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_has_campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_has_campaign` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `campaign_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Project_has_Campaign_Campaign1_idx` (`campaign_id` ASC),
  INDEX `fk_Project_has_Campaign_Project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_Project_has_Campaign_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_Campaign_Campaign1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `mydb`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`report` (
  `id` INT NOT NULL,
  `report_type` VARCHAR(45) NOT NULL,
  `project_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Report_Project1_idx` (`project_Id` ASC),
  CONSTRAINT `fk_Report_Project1`
    FOREIGN KEY (`project_Id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`expenses` (
  `id` INT NOT NULL,
  `expenses_report` VARCHAR(45) NOT NULL,
  `report_Id` INT NOT NULL,
  `report_project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Expenses_Report1_idx` (`report_Id` ASC, `report_project_id` ASC),
  CONSTRAINT `fk_Expenses_Report1`
    FOREIGN KEY (`report_Id` , `report_project_id`)
    REFERENCES `mydb`.`report` (`id` , `project_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin_has_project` (
  `id` VARCHAR(45) NOT NULL,
  `admin_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Admin_has_Project_Project1_idx` (`project_id` ASC),
  INDEX `fk_Admin_has_Project_Admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_Admin_has_Project_Admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admin_has_Project_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_has_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin_has_report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_id` INT NOT NULL,
  `report_Id` INT NOT NULL,
  INDEX `fk_Admin_has_Report_Report1_idx` (`report_Id` ASC),
  INDEX `fk_Admin_has_Report_Admin1_idx` (`admin_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Admin_has_Report_Admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admin_has_Report_Report1`
    FOREIGN KEY (`report_Id`)
    REFERENCES `mydb`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
